AWSTemplateFormatVersion: "2010-09-09"
Description: "Batch Job Resources"
Resources:
  EMRFS:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      AccessControl: "BucketOwnerFullControl"
      VersioningConfiguration:
        Status: "Enabled"
      LifecycleConfiguration:
        Rule:
          id: "clean-up-incomplete-multipart-upload"
          Status: "Enabled"
          AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 7
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-EMRFS"
        - Key: "Owner"
          Value: !Ref AWS::StackName
  TestCluster: 
    Type: "AWS::EMR::Cluster"
    Properties: 
      BootstrapActions: 
        - 
          Name: "WordCountJob"
          ScriptBootstrapAction: 
            Path: "/path/to/s3"
      Instances: 
        MasterInstanceGroup: 
          InstanceCount: 1
          InstanceType: "m3.xlarge"
          Market: "ON_DEMAND"
          Name: "Master"
        CoreInstanceGroup: 
          InstanceCount: 2
          InstanceType: "m3.xlarge"
          Market: "ON_DEMAND"
          Name: "Core"
        TerminationProtected: false
      Name: "WordCountCluster"
      JobFlowRole: "EMR_EC2_DefaultRole"
      ScaleDownBehavior: "TERMINATE_AT_TASK_COMPLETION"
      ServiceRole: "EMR_DefaultRole"
      ReleaseLabel: "emr-5.19.0"
      Tags: 
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-emr-cluster"
        - Key: "Owner"
          Value: !Sub "${AWS::StackName}"
